/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package puzzle;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class Main extends Application{
    public static void main(String[] args) {
        launch(args);
    }

    public void start(Stage primaryStage)throws Exception{
        puzzle fifPuz = new puzzle();
        int numberOfTiles = 16;
        Label[] tiles = new Label[numberOfTiles];
        Pane pane = new Pane();
        
        fifPuz.initialContent(numberOfTiles, tiles);
        pane.getChildren().addAll(tiles);

        for(int i =0; i<4 ; i++){
            tiles[i].setLayoutX(50*i);
            tiles[i].setLayoutY(0);
        }
        for(int i =4; i<8 ; i++){
            tiles[i].setLayoutX(50*(i-4));
            tiles[i].setLayoutY(50);
        }
        for(int i =8; i<12 ; i++){
            tiles[i].setLayoutX(50*(i-8));
            tiles[i].setLayoutY(100);
        }
        for(int i =12; i<16 ; i++){
            tiles[i].setLayoutX(50*(i-12));
            tiles[i].setLayoutY(150);
        }
        
        fifPuz.blankPosition(tiles);
        fifPuz.tilesMovement(pane,tiles);

        Scene scene = new Scene(pane);
        primaryStage.setScene(scene);
        primaryStage.setTitle("15 Puzzle");
        primaryStage.show();
    }
}
