/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package oop.final.kelompok.a;

public class FifteenPuzzle{
    public FifteenPuzzle(){

    }

    public String Start() {
        return "Tampilan awal";
    }

    public void playingGrid(){

    }

    public boolean solveCheck(){
        //
        return true;
    }

    public void numberTiles(){
        
    }

    public void shufflePuzzle(){
        
    }

    public void reset(){
        
    }

    

    public static void main(String[] args) {
        System.out.println(new App().Start());
    }
}
