/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package oop.final.kelompok.a;

public class Main {
    public static void main(String[] args) {
        System.out.println("15 Puzzle");
    }
}